name: Deploy Bronze Ingestion Framework Scripts to S3

# This triggers the workflow only when you push to the 'main' branch
# and only if files inside the 'scripts/' folder are changed.
on:
  push:
    branches:
      - main
    paths:
      - 'bronze_ingestion_framework/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # Standard region for India, change if your S3 bucket is elsewhere
        aws-region: us-east-1 

    - name: Package Modular Dependencies
      run: |
        echo "Zipping the modular folders for AWS Glue worker nodes..."
        # Navigate into your specific project folder
        cd bronze_ingestion_framework
        
        # Zip only the module directories into dependencies.zip
        zip -r dependencies.zip config/ readers/ processors/ writers/

    - name: Sync scripts to S3
      run: |
        # Sync the local framework folder directly to your S3 scripts path
        aws s3 sync ./bronze_ingestion_framework s3://medallion-dev-ops-use1/scripts/ --delete